name: EV Charger Alert Scheduler

on:
  schedule:
    # Runs every 15 minutes
    - cron: '*/15 * * * *'
  workflow_dispatch:
    # Allows manual triggering of the workflow

jobs:
  check-charger-alert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run check alert script
        run: |
          bash .github/scripts/check_alert.sh "https://evc-alert-app.streamlit.app/?api=check_alert"